version: '3.7'

services:

  ### NodeJS Container ###########################
  nodejs:
    build:
      context: ./docker/nodejs
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    network_mode: host
    ports:
      - '3000:3000'
    volumes:
      - ./:/var/www
    tty: false